### ISSUE TITLE
[BUG] Failed to create detector: [security_analytics_exception] analyzer [rule_analyzer] has not been configured in mappings

### ISSUE THREAD

**Issue by CyberAbwehr** [opensearch-project/security-analytics#319]
**What is the bug?**
create a new Security Analytics Detector 
ERROR: Failed to create detector:
[security_analytics_exception] analyzer [rule_analyzer] has not been configured in mappings 

**How can one reproduce the bug?**
1. Go to Security Analytics and create a new detector

**What is the expected behavior?**
Want to create a detector based on auditbeat 7.13.4 logs to find with the SIMGA rule "System Network Discovery - Linux"

**What is your host/environment?**
 - OS: Ubuntu bullseye/sid
 - Version 2.5.0
 - Plugins logtash 8.4.0, opensearch-security-analytics 2.5.0.0

**Do you have any screenshots?**
opensearch node log

Caused by: java.lang.Exception: java.lang.IllegalArgumentException: analyzer [rule_analyzer] has not been configured in mappings
	... 9 more
uncaught exception in thread [DefaultDispatcher-worker-1]
AlertingException[analyzer [rule_analyzer] has not been configured in mappings]; nested: Exception[java.lang.IllegalArgumentException: analyzer [rule_analyzer] has not been configured in mappings];
	at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70)
	at org.opensearch.alerting.util.DocLevelMonitorQueries.updateQueryIndexMappings(DocLevelMonitorQueries.kt:359)
	at org.opensearch.alerting.util.DocLevelMonitorQueries.access$updateQueryIndexMappings(DocLevelMonitorQueries.kt:41)
	at org.opensearch.alerting.util.DocLevelMonitorQueries$updateQueryIndexMappings$1.invokeSuspend(DocLevelMonitorQueries.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:285)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.lang.Exception: java.lang.IllegalArgumentException: analyzer [rule_analyzer] has not been configured in mappings
	... 9 more
[2023-01-24T17:35:14,004][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-alerts/usv-AHTXR_KClWRreCZqWQ]
[2023-01-24T17:35:14,013][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-alerts-history-2023.01.23-1/OypQ-vxZRC-h-FaAw89axA]
[2023-01-24T17:35:14,018][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-findings-2023.01.23-1/W_-cMmlGTD20B9oFf5HiLA]
[2023-01-24T17:35:14,025][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-detectors-queries-000001/T_nv-1T0Rb2zgim5THXltg]
[2023-01-24T17:35:14,176][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-alerts/usv-AHTXR_KClWRreCZqWQ]
[2023-01-24T17:35:14,185][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-alerts-history-2023.01.23-1/OypQ-vxZRC-h-FaAw89axA]
[2023-01-24T17:35:14,190][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-findings-2023.01.23-1/W_-cMmlGTD20B9oFf5HiLA]
[2023-01-24T17:35:14,199][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-detectors-queries-000001/T_nv-1T0Rb2zgim5THXltg]
[2023-01-24T17:35:14,392][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-alerts/usv-AHTXR_KClWRreCZqWQ]
[2023-01-24T17:35:14,397][INFO ][o.o.a.a.AlertIndices     ] [opensearch-node1] Index mapping of .opensearch-sap-linux-alerts is updated
[2023-01-24T17:35:14,404][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-alerts-history-2023.01.23-1/OypQ-vxZRC-h-FaAw89axA]
[2023-01-24T17:35:14,407][INFO ][o.o.a.a.AlertIndices     ] [opensearch-node1] Index mapping of .opensearch-sap-linux-alerts-history-2023.01.23-1 is updated
[2023-01-24T17:35:14,414][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-findings-2023.01.23-1/W_-cMmlGTD20B9oFf5HiLA]
[2023-01-24T17:35:14,415][INFO ][o.o.a.a.AlertIndices     ] [opensearch-node1] Index mapping of .opensearch-sap-linux-findings-2023.01.23-1 is updated
[2023-01-24T17:35:14,421][INFO ][o.o.p.PluginsService     ] [opensearch-node1] PluginService:onIndexModule index:[.opensearch-sap-linux-detectors-queries-000001/T_nv-1T0Rb2zgim5THXltg]
[2023-01-24T17:35:14,422][ERROR][o.o.a.u.AlertingException] [opensearch-node1] Alerting error: java.lang.IllegalArgumentException: analyzer [rule_analyzer] has not been configured in mappings
[2023-01-24T17:35:14,422][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [opensearch-node1] uncaught exception in thread [DefaultDispatcher-worker-1]
org.opensearch.alerting.util.AlertingException: analyzer [rule_analyzer] has not been configured in mappings
	at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70) ~[opensearch-alerting-2.5.0.0.jar:2.5.0.0]
	at org.opensearch.alerting.util.DocLevelMonitorQueries.updateQueryIndexMappings(DocLevelMonitorQueries.kt:359) ~[opensearch-alerting-2.5.0.0.jar:2.5.0.0]
	at org.opensearch.alerting.util.DocLevelMonitorQueries.access$updateQueryIndexMappings(DocLevelMonitorQueries.kt:41) ~[opensearch-alerting-2.5.0.0.jar:2.5.0.0]
	at org.opensearch.alerting.util.DocLevelMonitorQueries$updateQueryIndexMappings$1.invokeSuspend(DocLevelMonitorQueries.kt) ~[opensearch-alerting-2.5.0.0.jar:2.5.0.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:285) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
Caused by: java.lang.Exception: java.lang.IllegalArgumentException: analyzer [rule_analyzer] has not been configured in mappings
	... 9 more
uncaught exception in thread [DefaultDispatcher-worker-1]
AlertingException[analyzer [rule_analyzer] has not been configured in mappings]; nested: Exception[java.lang.IllegalArgumentException: analyzer [rule_analyzer] has not been configured in mappings];
	at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70)
	at org.opensearch.alerting.util.DocLevelMonitorQueries.updateQueryIndexMappings(DocLevelMonitorQueries.kt:359)
	at org.opensearch.alerting.util.DocLevelMonitorQueries.access$updateQueryIndexMappings(DocLevelMonitorQueries.kt:41)
	at org.opensearch.alerting.util.DocLevelMonitorQueries$updateQueryIndexMappings$1.invokeSuspend(DocLevelMonitorQueries.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:285)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.lang.Exception: java.lang.IllegalArgumentException: analyzer [rule_analyzer] has not been configured in mappings
	... 9 more

**Comment by petardz** [comment]
Is there a chance that you have V2 index template with pattern which covers .opensearch-sap* ?

**Comment by CyberAbwehr** [comment]
When I start logstash the following template is used.

[2023-01-30T07:29:05,808][INFO ][logstash.outputs.opensearch][main] Using a default mapping template {:version=>2, :ecs_compatibility=>:v8}

Full logstash log:
[2023-01-30T07:28:58,999][INFO ][logstash.runner ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties
[2023-01-30T07:28:59,024][INFO ][logstash.runner ] Starting Logstash {"logstash.version"=>"8.4.0", "jruby.version"=>"jruby 9.3.6.0 (2.6. 8) 2022-06-27 7a2cbcd376 OpenJDK 64-Bit Server VM 17.0.4+8 on 17.0.4+8 +indy +jit [x86_64-linux]"}
[2023-01-30T07:28:59,026][INFO ][logstash.runner ] JVM bootstrap flags: [-Xms1g, -Xmx1g, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djruby .compile.invokedynamic=true, -Djruby.jit.threshold=0, -XX:+HeapDumpOnOutOfMemoryError, -Djava.security.egd=file:/dev/urandom, -Dlog4j2.isThreadContextMapInheritable=true, -Dls.cgroup.cpuacct. path.override=/, -Dls.cgroup.cpu.path.override=/, -Djruby.regexp.interruptible=true, -Djdk.io.File.enableADS=true, --add-exports=jdk.compiler/com .sun.tools.javac.api=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun .tools.javac.parser=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools .javac.util=ALL-UNNAMED, --add-opens=java.base/java.security=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens =java.base/java.nio.channels=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, --add-opens=java.manage ment/sun.management=ALL-UNNAMED]
[2023-01-30T07:29:01,077][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600, :ssl_enabled=>false}
[2023-01-30T07:29:01,808][INFO ][org.reflections.Reflections] Reflections took 153 ms to scan 1 urls, producing 125 keys and 434 values
[2023-01-30T07:29:04,636][INFO ][logstash.javapipeline ] Pipeline `main` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2023-01-30T07:29:04,714][INFO ][logstash.outputs.opensearch][main] New OpenSearch output {:class=>"LogStash::Outputs::OpenSearch", :hosts=>["https: //192.168.56.108:9200"]}
[2023-01-30T07:29:04,765][WARN ][logstash.outputs.opensearch][main] ** WARNING ** Detected UNSAFE options in opensearch output configuration!
** WARNING ** You have enabled encryption but DISABLED certificate verification.
** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true
[2023-01-30T07:29:05,053][INFO ][logstash.outputs.opensearch][main] OpenSearch pool URLs updated {:changes=>{:removed=>[], :added=>[https:// admin:xxxxxx@192.168.56.108:9200/]}}
[2023-01-30T07:29:05,586][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://admin:xxxxxx@192.168.56.108:9200/" }
[2023-01-30T07:29:05,667][INFO ][logstash.outputs.opensearch][main] Cluster version determined (2.5.0) {:version=>2}
[2023-01-30T07:29:05,808][INFO ][logstash.outputs.opensearch][main] Using a default mapping template {:version=>2, :ecs_compatibility=>:v8}
[2023-01-30T07:29:05,841][INFO ][logstash.javapipeline ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>1, "pipeline.batch.size"= >125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["/usr/share/logstash/pipeline/logstash.conf"], :thread= >"#<Thread:0x5bb5d35d run>"}
[2023-01-30T07:29:07,227][INFO ][logstash.javapipeline ][main] Pipeline Java execution initialization time {"seconds"=>1.36}
[2023-01-30T07:29:07,264][INFO ][logstash.inputs.beats ][main] Starting input listener {:address=>"0.0.0.0:5044"}
[2023-01-30T07:29:07,280][INFO ][logstash.javapipeline ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-01-30T07:29:07,369][INFO ][logstash.agent ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-01-30T07:29:07,440][INFO ][org.logstash.beats.Server][main][bf34f3b6d68ff47817d658bd941ee537dd4cfa11f824da94cc0a13d9c4c5792b] Starting server on port: 5044

**Comment by CyberAbwehr** [comment]
GET _cat/templates

ecs-logstash                                             [ecs-logstash-*] 1           
tenant_template                                          [.kibana_-*_*, .kibana_0*_*, .kibana_1*_*, .kibana_2*_*, .kibana_3*_*, .kibana_4*_*, .kibana_5*_*, .kibana_6*_*, .kibana_7*_*, .kibana_8*_*, .kibana_9*_*]                                                                                    2147483647  
.opensearch-sap-detectors-queries-index-template         [.opensearch-sap-s3-detectors-queries*, .opensearch-sap-others_compliance-detectors-queries*, .opensearch-sap-others_application-detectors-queries*, .opensearch-sap-dns-detectors-queries*, .opensearch-sap-others_cloud-detectors-queries*, .opensearch-sap-others_web-detectors-queries*, .opensearch-sap-windows-detectors-queries*, .opensearch-sap-cloudtrail-detectors-queries*, .opensearch-sap-others_macos-detectors-queries*, .opensearch-sap-ad_ldap-detectors-queries*, .opensearch-sap-test_windows-detectors-queries*, .opensearch-sap-network-detectors-queries*, .opensearch-sap-apache_access-detectors-queries*, .opensearch-sap-linux-detectors-queries*, .opensearch-sap-others_apt-detectors-queries*, .opensearch-sap-others_proxy-detectors-queries*] 0           
.opensearch-sap-alias-mappings-index-template-auditbeat- [auditbeat-*] 0           [.opensearch-sap-alias-mappings-component-auditbeat-]

**Comment by a-khov** [comment]
Hi! Check your index settings. Manualy adding settings to the index .opensearch-sap-linux-detectors-queries-000001 helped me. In your case it maybe another index, like ".opensearch-sap-linux-detectors-queries-000002"

On devtools do:
PUT .opensearch-sap-linux-detectors-queries-000001
{
 "settings": {
  "analysis": {
          "analyzer": {
            "rule_analyzer": {
              "char_filter": [
                "rule_ws_filter"
              ],
              "tokenizer": "keyword"
            }
          },
          "char_filter": {
            "rule_ws_filter": {
              "pattern": "(_ws_)",
              "type": "pattern_replace",
              "replacement": " "
            }
          }
  }
 }
}

**Comment by CyberAbwehr** [comment]
it looks like that it is still there.

{
  "error": {
    "root_cause": [
      {
        "type": "resource_already_exists_exception",
        "reason": "index [.opensearch-sap-linux-detectors-queries-000001/eZKLq8OpROSVdS1D9zzOLg] already exists",
        "index": ".opensearch-sap-linux-detectors-queries-000001",
        "index_uuid": "eZKLq8OpROSVdS1D9zzOLg"
      }
    ],
    "type": "resource_already_exists_exception",
    "reason": "index [.opensearch-sap-linux-detectors-queries-000001/eZKLq8OpROSVdS1D9zzOLg] already exists",
    "index": ".opensearch-sap-linux-detectors-queries-000001",
    "index_uuid": "eZKLq8OpROSVdS1D9zzOLg"
  },
  "status": 400
}

**Comment by a-khov** [comment]
In my case, I deleted the problematic index and it was created anew. But the number of indexes .opensearch-sap-linux-detectors-queries-xxxxxx is growing enormously

**Comment by AESthetix256** [comment]
Same here, 
we have configured two clusters - for some reason it works on one cluster, but on the other cluster .opensearch-sap-linux-detectors-queries-xxxxxx is creating new indices as well. 
I'll keep you updated if we find whats wrong!

**Comment by AESthetix256** [comment]
Not the solution but a difference I found between the two clusters:

NOK:
`green open .opensearch-sap-linux-detectors-queries-000002 62ngm4GKS2-xyj_sJlTpkg 1 1 0 0 416b 208b`
`green open .opensearch-sap-linux-detectors-queries-000001 b4KS2zJqTb-12N9SmK9wUw 1 1 0 0 208b 208b`

OK:
`green open .opensearch-sap-dns-detectors-queries-000001      -VF8oH9uShKPdw4et4HeCw 1 1    12    24  80.9kb 41.2kb`
`green open .opensearch-sap-linux-detectors-queries-000001    VhEFcSxvTqmoAPVF1wwA_A 1 1   119     0 141.9kb 70.9kb`

for example the linux-queries index is way bigger on the working cluster - so there must be something wrong when creating the queries index and it just retries again and again.

**Comment by AESthetix256** [comment]
`green open .opensearch-sap-pre-packaged-rules-config           bOuG4pIiSwiWz9fJWTdP8Q 1 1 17244 12  7.9mb   4mb`
`green open .opensearch-sap-pre-packaged-rules-config         UsQRm7d-RDiFBn3ylGFOLw 1 1 17244 12  38.6mb 19.4mb`

The Pre-Packaged Config is way smaller as well, even though i used an ansible script to setup both clusters, so those should be the same.

**Comment by CyberAbwehr** [comment]
This will fix the linux mapping problem, still tested.

https://github.com/opensearch-project/security-analytics/pull/320

**Comment by a-khov** [comment]
It turned out to stop the growth of indexes apache_access-detectors-queries by increasing the number of fields in the index. On DevTools

PUT .opensearch-sap-apache_access-detectors-queries*/_settings
{
  "index.mapping.total_fields.limit": 3000
}

**Comment by french-kiwy** [comment]
We observe similar effect with winlogbeats and windows detector.  
Our only solution for now has been to fully disable security analytics and remove any trace of template or index we can find related to security analytics and still we can see the indices created but at least there's no constant rollover messing with the max number of shard we can manage.  
For now our only way to use the security analitics would be to reinstall from scratch.

**Comment by petardz** [comment]
Can you please update to 2.5 and try? This issue should be fixed,

It would be safest to cleanup all SAP/Alerting created indices if you can.

**Comment by french-kiwy** [comment]
We already upgrade from 2.4 to 2.5 recently. 
We tried to remove all the indices named ´.opensearch-sap-windows*´ and they keep being recreated. but now at least they stopped rollovering.  
The detectors have been created after the upgrade.  
Is there a simple way to remove all indices from security analitics so we can renable it without it going wild ?

**Comment by petardz** [comment]
I'm sorry I mistyped: upgrade to 2.6

Issue with total_fields limit has been fixed completly in 2.6
