### ISSUE TITLE
[BUG] security_analytics_exception, Create detector failed

### ISSUE THREAD

**Issue by StefanSa** [opensearch-project/security-analytics#498]
**What is the bug?**
Wanted to build the sample-detector like playground with opensearch_dashboards_sample_data_logs and apache_access,
but get this error message when saving the detectors.
```
Create detector failed.
[security_analytics_exception]
```

**How can one reproduce the bug?**
Use the detector wizard and try to save. 

**What is the expected behavior?**
Successfully create a detector without any problems.

**What is your host/environment?**
- OS: [Windows 11]
- Version [opensearch 2.9]
- 3 client, master and data nodes

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/security-analytics-dashboards-plugin/assets/6105075/be489bc6-f2cd-4bcc-9c19-ab7ce736c7c1)

**Do you have any additional context?**
opensearch-dashboard log:
```
2023-07-25T11:12:53.366511+02:00 os-dash01 opensearch-dashboards[7806]: Security Analytics - DetectorsService - createDetector: StatusCodeError: [security_analytics_exception] [os-master02][172.16.34.214:9300][indices:admin/mapping/put]
2023-07-25T11:12:53.366592+02:00 os-dash01 opensearch-dashboards[7806]:     at respond (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:349:15)
2023-07-25T11:12:53.366622+02:00 os-dash01 opensearch-dashboards[7806]:     at checkRespForFailure (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:306:7)
2023-07-25T11:12:53.366649+02:00 os-dash01 opensearch-dashboards[7806]:     at HttpConnector.<anonymous> (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
2023-07-25T11:12:53.366676+02:00 os-dash01 opensearch-dashboards[7806]:     at IncomingMessage.wrapper (/usr/share/opensearch-dashboards/node_modules/lodash/lodash.js:4991:19)
2023-07-25T11:12:53.366701+02:00 os-dash01 opensearch-dashboards[7806]:     at IncomingMessage.emit (node:events:525:35)
2023-07-25T11:12:53.366748+02:00 os-dash01 opensearch-dashboards[7806]:     at IncomingMessage.emit (node:domain:489:12)
2023-07-25T11:12:53.366774+02:00 os-dash01 opensearch-dashboards[7806]:     at endReadableNT (node:internal/streams/readable:1358:12)
2023-07-25T11:12:53.366797+02:00 os-dash01 opensearch-dashboards[7806]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2023-07-25T11:12:53.366820+02:00 os-dash01 opensearch-dashboards[7806]:   status: 500,
2023-07-25T11:12:53.366847+02:00 os-dash01 opensearch-dashboards[7806]:   displayName: 'InternalServerError',
2023-07-25T11:12:53.366870+02:00 os-dash01 opensearch-dashboards[7806]:   path: '/_plugins/_security_analytics/detectors',
2023-07-25T11:12:53.366893+02:00 os-dash01 opensearch-dashboards[7806]:   query: {},
2023-07-25T11:12:53.366916+02:00 os-dash01 opensearch-dashboards[7806]:   body: {
2023-07-25T11:12:53.366939+02:00 os-dash01 opensearch-dashboards[7806]:     error: {
2023-07-25T11:12:53.366961+02:00 os-dash01 opensearch-dashboards[7806]:       root_cause: [Array],
2023-07-25T11:12:53.366984+02:00 os-dash01 opensearch-dashboards[7806]:       type: 'security_analytics_exception',
2023-07-25T11:12:53.367007+02:00 os-dash01 opensearch-dashboards[7806]:       reason: '[os-master02][172.16.34.214:9300][indices:admin/mapping/put]',
2023-07-25T11:12:53.367030+02:00 os-dash01 opensearch-dashboards[7806]:       caused_by: [Object]
2023-07-25T11:12:53.367055+02:00 os-dash01 opensearch-dashboards[7806]:     },
2023-07-25T11:12:53.367080+02:00 os-dash01 opensearch-dashboards[7806]:     status: 500
2023-07-25T11:12:53.367103+02:00 os-dash01 opensearch-dashboards[7806]:   },
2023-07-25T11:12:53.367129+02:00 os-dash01 opensearch-dashboards[7806]:   statusCode: 500,
2023-07-25T11:12:53.367153+02:00 os-dash01 opensearch-dashboards[7806]:   response: '{"error":{"root_cause":[{"type":"security_analytics_exception","reason":"[os-master02][172.16.34.214:9300][indices:admin/mapping/put]"}],"type":"security_analytics_exception","reason":"[os-master02][172.16.34.214:9300][indices:admin/mapping/put]","caused_by":{"type":"exception","reason":"org.opensearch.alerting.util.AlertingException: [os-master02][172.16.34.214:9300][indices:admin/mapping/put]"}},"status":500}',
2023-07-25T11:12:53.367185+02:00 os-dash01 opensearch-dashboards[7806]:   toString: [Function (anonymous)],
2023-07-25T11:12:53.367209+02:00 os-dash01 opensearch-dashboards[7806]:   toJSON: [Function (anonymous)]
2023-07-25T11:12:53.367234+02:00 os-dash01 opensearch-dashboards[7806]: }
```

**Comment by StefanSa** [comment]
I have the same problem on playground,
currently this really interesting tool is not usable for me.

**Comment by sbcd90** [comment]
hi @StefanSa , this may be an issue with alerting config indices.
Please delete the alerting config indices & re-create them.
```
.opendistro-alerting-config
````

**Comment by StefanSa** [comment]
@sbcd90 
thank you, that had been the solution.

**Comment by jhill-cmd** [comment]
@sbcd90 @StefanSa ok for the delete, but  it will recreate by itself ? where do I get the data to be able to recreate it ?
