### ISSUE TITLE
Security test CI failing on 2.11 https://github.com/opensearch-project/security-analytics/actions/runs/6619014281/job/18020314290

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/security-analytics#685]
```
2023-10-24T22:26:54.8823262Z » ERROR][o.o.a.u.AlertingException] [integTest-0] Alerting error: RemoteTransportException[[integTest-1][127.0.0.1:42729][indices:admin/mapping/put]]; nested: IllegalArgumentException[mapper [workflow.schedule.period.unit] cannot be changed from type [text] to [keyword]];
2023-10-24T22:26:54.8825630Z » ERROR][o.o.s.t.TransportIndexDetectorAction] [integTest-0] exception:
2023-10-24T22:26:54.8826958Z »  org.opensearch.alerting.util.AlertingException: [integTest-1][127.0.0.1:42729][indices:admin/mapping/put]
2023-10-24T22:26:54.8828519Z »  	at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70) ~[?:?]
2023-10-24T22:26:54.8830457Z »  	at org.opensearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler$start$2.onFailure(TransportIndexMonitorAction.kt:354) ~[?:?]
2023-10-24T22:26:54.8832794Z »  	at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:122) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8874743Z »  	at org.opensearch.action.support.RetryableAction$RetryingListener.onFinalFailure(RetryableAction.java:218) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8877155Z »  	at org.opensearch.action.support.RetryableAction$RetryingListener.onFailure(RetryableAction.java:210) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8880256Z »  	at org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction$AsyncSingleAction$1.handleException(TransportClusterManagerNodeAction.java:300) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8882995Z »  	at org.opensearch.transport.TransportService$6.handleException(TransportService.java:903) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8885387Z »  	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1526) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8887769Z »  	at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:438) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8890309Z »  	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:343) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8892672Z »  	at org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:436) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8894804Z »  	at org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:428) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8896911Z »  	at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:166) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8898995Z »  	at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:123) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8901050Z »  	at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:770) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8903100Z »  	at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8905202Z »  	at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8907264Z »  	at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8909290Z »  	at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:95) ~[?:?]
2023-10-24T22:26:54.8911498Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
2023-10-24T22:26:54.8913427Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
2023-10-24T22:26:54.8915319Z »  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
2023-10-24T22:26:54.8916931Z »  	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[?:?]
2023-10-24T22:26:54.8918566Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
2023-10-24T22:26:54.8920471Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
2023-10-24T22:26:54.8922345Z »  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
2023-10-24T22:26:54.8924260Z »  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
2023-10-24T22:26:54.8926045Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
2023-10-24T22:26:54.8927953Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
2023-10-24T22:26:54.8929796Z »  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
2023-10-24T22:26:54.8931396Z »  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
2023-10-24T22:26:54.8932889Z »  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
2023-10-24T22:26:54.8934321Z »  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) ~[?:?]
2023-10-24T22:26:54.8935752Z »  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) ~[?:?]
2023-10-24T22:26:54.8936981Z »  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
2023-10-24T22:26:54.8938345Z »  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
2023-10-24T22:26:54.8939789Z »  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
2023-10-24T22:26:54.8940761Z »  	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-10-24T22:26:54.8942214Z »  Caused by: java.lang.Exception: org.opensearch.transport.RemoteTransportException: [integTest-1][127.0.0.1:42729][indices:admin/mapping/put]
2023-10-24T22:26:54.8943453Z »  	... 38 more
2023-10-24T22:26:54.8944221Z » ERROR][o.o.s.u.SecurityAnalyticsException] [integTest-0] Security Analytics error:
2023-10-24T22:26:54.8945625Z »  org.opensearch.alerting.util.AlertingException: [integTest-1][127.0.0.1:42729][indices:admin/mapping/put]
2023-10-24T22:26:54.8947175Z »  	at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70) ~[?:?]
2023-10-24T22:26:54.8949141Z »  	at org.opensearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler$start$2.onFailure(TransportIndexMonitorAction.kt:354) ~[?:?]
2023-10-24T22:26:54.8951317Z »  	at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:122) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8953564Z »  	at org.opensearch.action.support.RetryableAction$RetryingListener.onFinalFailure(RetryableAction.java:218) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8955918Z »  	at org.opensearch.action.support.RetryableAction$RetryingListener.onFailure(RetryableAction.java:210) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8958804Z »  	at org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction$AsyncSingleAction$1.handleException(TransportClusterManagerNodeAction.java:300) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8961695Z »  	at org.opensearch.transport.TransportService$6.handleException(TransportService.java:903) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8964062Z »  	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1526) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.8966436Z »  	at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:438) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9061353Z »  	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:343) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9064025Z »  	at org.opensearch.transport.InboundHandler.handleException(InboundHandler.java:436) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9066144Z »  	at org.opensearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:428) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9068716Z »  	at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:166) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9070793Z »  	at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:123) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9072814Z »  	at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:770) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9074855Z »  	at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9076951Z »  	at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9078996Z »  	at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9081032Z »  	at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:95) ~[?:?]
2023-10-24T22:26:54.9082978Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
2023-10-24T22:26:54.9084870Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
2023-10-24T22:26:54.9086757Z »  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
2023-10-24T22:26:54.9088505Z »  	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[?:?]
2023-10-24T22:26:54.9090149Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
2023-10-24T22:26:54.9092047Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
2023-10-24T22:26:54.9093948Z »  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
2023-10-24T22:26:54.9095695Z »  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
2023-10-24T22:26:54.9097490Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
2023-10-24T22:26:54.9099388Z »  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
2023-10-24T22:26:54.9101135Z »  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
2023-10-24T22:26:54.9102741Z »  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
2023-10-24T22:26:54.9104237Z »  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
2023-10-24T22:26:54.9105680Z »  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) ~[?:?]
2023-10-24T22:26:54.9107272Z »  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) ~[?:?]
2023-10-24T22:26:54.9108494Z »  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
2023-10-24T22:26:54.9109855Z »  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
2023-10-24T22:26:54.9111301Z »  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
2023-10-24T22:26:54.9112275Z »  	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-10-24T22:26:54.9113743Z »  Caused by: java.lang.Exception: org.opensearch.transport.RemoteTransportException: [integTest-1][127.0.0.1:42729][indices:admin/mapping/put]
2023-10-24T22:26:54.9114972Z »  	... 38 more
2023-10-24T22:26:54.9115789Z » WARN ][r.suppressed             ] [integTest-0] path: /_plugins/_security_analytics/detectors, params: {}
2023-10-24T22:26:54.9117630Z »  org.opensearch.securityanalytics.util.SecurityAnalyticsException: [integTest-1][127.0.0.1:42729][indices:admin/mapping/put]
2023-10-24T22:26:54.9119573Z »  	at org.opensearch.securityanalytics.util.SecurityAnalyticsException.wrap(SecurityAnalyticsException.java:68) ~[?:?]
2023-10-24T22:26:54.9121520Z »  	at org.opensearch.securityanalytics.util.SecurityAnalyticsException.wrap(SecurityAnalyticsException.java:43) ~[?:?]
2023-10-24T22:26:54.9123870Z »  	at org.opensearch.securityanalytics.transport.TransportIndexDetectorAction$AsyncIndexDetectorsAction.lambda$finishHim$0(TransportIndexDetectorAction.java:1477) ~[?:?]
2023-10-24T22:26:54.9126205Z »  	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74) [opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9181644Z »  	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9184253Z »  	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9186681Z »  	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9188449Z »  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2023-10-24T22:26:54.9189842Z »  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2023-10-24T22:26:54.9190871Z »  	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-10-24T22:26:54.9192274Z »  Caused by: java.lang.Exception: org.opensearch.alerting.util.AlertingException: [integTest-1][127.0.0.1:42729][indices:admin/mapping/put]
2023-10-24T22:26:54.9193495Z »  	... 10 more
2023-10-24T22:26:54.9194269Z » ERROR][o.o.a.MonitorRunnerService] [integTest-0] Failed to update config index schema
2023-10-24T22:26:54.9195725Z »  org.opensearch.transport.RemoteTransportException: [integTest-1][127.0.0.1:42729][indices:admin/mapping/put]
2023-10-24T22:26:54.9197588Z »  Caused by: java.lang.IllegalArgumentException: mapper [workflow.schedule.period.unit] cannot be changed from type [text] to [keyword]
2023-10-24T22:26:54.9199745Z »  	at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:112) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9202024Z »  	at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:76) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9204085Z »  	at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:621) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9205988Z »  	at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:580) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9207873Z »  	at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:607) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9210283Z »  	at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:580) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9212159Z »  	at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:607) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9214044Z »  	at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:580) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9215926Z »  	at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:607) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9217913Z »  	at org.opensearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:351) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9219844Z »  	at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:580) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9221788Z »  	at org.opensearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:346) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9223799Z »  	at org.opensearch.index.mapper.Mapping.merge(Mapping.java:128) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9225618Z »  	at org.opensearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:307) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9227944Z »  	at org.opensearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.applyRequest(MetadataMappingService.java:283) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9230606Z »  	at org.opensearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.execute(MetadataMappingService.java:244) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9232949Z »  	at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:874) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9235154Z »  	at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:424) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9237289Z »  	at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:295) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9239338Z »  	at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:206) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9241421Z »  	at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:204) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9243488Z »  	at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:242) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9245708Z »  	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9248919Z »  	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9252576Z »  	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245) ~[opensearch-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
2023-10-24T22:26:54.9255007Z »  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
2023-10-24T22:26:54.9256393Z »  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
2023-10-24T22:26:54.9257429Z »  	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by eirsep** [comment]
https://github.com/opensearch-project/security-analytics/actions/runs/6619014281/job/18020314290

**Comment by eirsep** [comment]
```
➜  security-analytics git:(282046d7) ✗ ./gradlew :integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=docker-cluster -Dhttps=true -Duser=admin -Dpassword=admin --tests  "org.opensearch.securityanalytics.alerts.AlertsIT.testAckAlerts_WithInvalidDetectorAlertsCombination"
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.2.1
  OS Info               : Mac OS X 13.5.1 (aarch64)
  JDK Version           : 17 (Amazon Corretto JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home
  Random Testing Seed   : A7A4D46D3DC52F06
  In FIPS 140 mode      : false
=======================================

> Task :integTestRemote
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
This is a flaky test.

Difficult to reproduce on local set up

**Comment by eirsep** [comment]
```
➜  security-analytics git:(282046d7) ✗ ./gradlew :integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=docker-cluster -Dhttps=true -Duser=admin -Dpassword=admin --tests  "org.opensearch.securityanalytics.alerts.AlertsIT.*"                                       
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.2.1
  OS Info               : Mac OS X 13.5.1 (aarch64)
  JDK Version           : 17 (Amazon Corretto JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home
  Random Testing Seed   : 863D2EC69580558
  In FIPS 140 mode      : false
=======================================

> Task :integTestRemote
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

**Comment by praveensameneni** [comment]
@sbcd90 , can you please check if this is still an issue -
Reference: https://github.com/opensearch-project/security-analytics/actions/runs/8887471505
