### ISSUE TITLE
[BUG] Unable to create detector

### ISSUE THREAD

**Issue by qw1mb0** [opensearch-project/security-analytics#830]
**What is the bug?**
It is not possible to create a detector in the UI. Is it possible to recreate all the necessary indexes/aliases for security analytics?

**How can one reproduce the bug?**
1. Go to 'Security Analytics page'
2. Click on 'Create detector' 
3. Select windows log type
4. Click 'Create'
5. See error
6. See error log:
```
[2024-02-04T16:52:50,482][INFO ][o.o.a.t.TransportIndexMonitorAction] [msk-it-siem-03] Central Percolation index .opensearch-sap-windows-detectors-que
ries created
[2024-02-04T16:52:50,490][ERROR][o.o.a.u.DocLevelMonitorQueries] [msk-it-siem-03] Failed to get write index for queryIndex alias:.opensearch-sap-windo
ws-detectors-queries
[2024-02-04T16:52:50,491][ERROR][o.o.a.u.AlertingException] [msk-it-siem-03] Alerting error: OpenSearchStatusException[Failed to get write index for q
ueryIndex alias:.opensearch-sap-windows-detectors-queries]
[2024-02-04T16:52:50,492][ERROR][o.o.a.t.TransportIndexMonitorAction] [msk-it-siem-03] failed to index doc level queries monitor mTBkdI0BHZISNeu3qIjH.
 deleting monitor
org.opensearch.alerting.util.AlertingException: Failed to get write index for queryIndex alias:.opensearch-sap-windows-detectors-queries
        at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70) ~[opensearch-alerting-2.11.1.0.jar:2.11.1.0]
        at org.opensearch.alerting.util.DocLevelMonitorQueries.updateQueryIndexMappings(DocLevelMonitorQueries.kt:407) ~[opensearch-alerting-2.11.1.0.
jar:2.11.1.0]
        at org.opensearch.alerting.util.DocLevelMonitorQueries.indexDocLevelQueries(DocLevelMonitorQueries.kt:284) ~[opensearch-alerting-2.11.1.0.jar:
2.11.1.0]
        at org.opensearch.alerting.util.DocLevelMonitorQueries$indexDocLevelQueries$1.invokeSuspend(DocLevelMonitorQueries.kt) ~[opensearch-alerting-2
.11.1.0.jar:2.11.1.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.8.21.jar:1.8.21-release-380(1.8.21)
]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
Caused by: java.lang.Exception: org.opensearch.OpenSearchStatusException: Failed to get write index for queryIndex alias:.opensearch-sap-windows-detec
tors-queries
        ... 9 more
[2024-02-04T16:52:50,540][ERROR][o.o.a.u.AlertingException] [msk-it-siem-03] Alerting error: AlertingException[Failed to get write index for queryInde
x alias:.opensearch-sap-windows-detectors-queries]; nested: Exception[org.opensearch.OpenSearchStatusException: Failed to get write index for queryInd
ex alias:.opensearch-sap-windows-detectors-queries];
[2024-02-04T16:52:50,541][ERROR][o.o.s.t.TransportIndexDetectorAction] [msk-it-siem-03] exception:
org.opensearch.alerting.util.AlertingException: Failed to get write index for queryIndex alias:.opensearch-sap-windows-detectors-queries
        at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70) ~[?:?]
        at org.opensearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler.indexMonitor(TransportIndexMonitorAction.kt:552) ~[?:?]
        at org.opensearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler.access$indexMonitor(TransportIndexMonitorAction.kt:251) ~
[?:?]
        at org.opensearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler$indexMonitor$1.invokeSuspend(TransportIndexMonitorAction.
kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) ~[?:?]
Caused by: java.lang.Exception: org.opensearch.alerting.util.AlertingException: Failed to get write index for queryIndex alias:.opensearch-sap-windows
-detectors-queries
        ... 9 more
[2024-02-04T16:52:50,543][ERROR][o.o.s.u.SecurityAnalyticsException] [msk-it-siem-03] Security Analytics error:
org.opensearch.alerting.util.AlertingException: Failed to get write index for queryIndex alias:.opensearch-sap-windows-detectors-queries
        at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70) ~[?:?]
        at org.opensearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler.indexMonitor(TransportIndexMonitorAction.kt:552) ~[?:?]
        at org.opensearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler.access$indexMonitor(TransportIndexMonitorAction.kt:251) ~
[?:?]
        at org.opensearch.alerting.transport.TransportIndexMonitorAction$IndexMonitorHandler$indexMonitor$1.invokeSuspend(TransportIndexMonitorAction.
kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) ~[?:?]
Caused by: java.lang.Exception: org.opensearch.alerting.util.AlertingException: Failed to get write index for queryIndex alias:.opensearch-sap-windows
-detectors-queries
        ... 9 more
[2024-02-04T16:52:50,544][WARN ][r.suppressed             ] [msk-it-siem-03] path: /_plugins/_security_analytics/detectors, params: {}
org.opensearch.securityanalytics.util.SecurityAnalyticsException: Failed to get write index for queryIndex alias:.opensearch-sap-windows-detectors-que
ries
        at org.opensearch.securityanalytics.util.SecurityAnalyticsException.wrap(SecurityAnalyticsException.java:68) ~[?:?]
        at org.opensearch.securityanalytics.util.SecurityAnalyticsException.wrap(SecurityAnalyticsException.java:43) ~[?:?]
        at org.opensearch.securityanalytics.transport.TransportIndexDetectorAction$AsyncIndexDetectorsAction.lambda$finishHim$0(TransportIndexDetector
Action.java:1474) ~[?:?]
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74) [opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.11.1.jar:
2.11.1]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.1.jar:2.11.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.Exception: org.opensearch.alerting.util.AlertingException: Failed to get write index for queryIndex alias:.opensearch-sap-windows
-detectors-queries
        ... 10 more
```

**What is the expected behavior?**
Successful creation of the detector.

**What is your host/environment?**
 - OS: Ubuntu 22.04.2
 - OpenSearch: 2.11.1
 - Plugins: security-analytics 2.11.1

**Do you have any screenshots?**
<img width="1307" alt="image" src="https://github.com/opensearch-project/security-analytics/assets/1931363/1bc8e774-750e-48b4-96b3-a343d5faba29">

<img width="1307" alt="image" src="https://github.com/opensearch-project/security-analytics/assets/1931363/e33baa11-b4e5-4e0b-8430-740e38fa908c">

**Comment by praveensameneni** [comment]
@qw1mb0 , can you please share any additional information on the version of OpenSearch - i.e did you upgrade from OpenSearch 2.5 to 2.11/2.12 recently? We added the concept of using alias for the query index (rules are copied to a system index as queries) in 2.7.

**Comment by jowg-amazon** [comment]
This error seems to be related to the fact that there is no alias called `.opensearch-sap-windows-detectors-queries` associated with the concrete windows query index. There is supposed to be an alias associated with each query index and should have have **one write** index associated with that alias. Your alias may have not been created, was somehow deleted, or may not have an index set as the write index. Here are the steps to manually create/fix this.  
1. Check see if the alias `.opensearch-sap-windows-detectors-queries` doesn't exist or if the alias doesn't have a designated write index: `GET _cat/aliases`
2. If this alias doesn't exist or doesn't have a write index, manually create it
3. First find the newest windows query index: `GET _cat/indices/.opensearch-sap-windows-detectors-queries-*'
4. Then create the alias on the newest windows query index:
```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": ".opensearch-sap-windows-detectors-queries-000001 (i.e. your newest created windows query index)",
        "alias": ".opensearch-sap-windows-detectors-queries",
        "is_write_index": true
      }
    }
  ]
}
```

**Comment by qw1mb0** [comment]
I updated OpenSearch to version 2.12, but when I try to create a detector I get an error:

```
[security_analytics_exception] Failed to get write index for queryIndex alias:.opensearch-sap-windows-detectors-queries
```

Existed aliases in opensearch:
```
$ curl -k -XGET -u 'admin:password' 'https://<ip>:9200/_cat/aliases' -s
.opendistro-alerting-alert-history-write .opendistro-alerting-alert-history-2024.03.16-000011     - - - -
.opensearch-sap-windows-alerts-history   .opensearch-sap-windows-alerts-history-2024.03.06-000002 - - - -
.opensearch-sap-windows-findings         .opensearch-sap-windows-findings-2024.03.06-000002       - - - -
```

There are also no indices  in the cluster (**.opensearch-sap-windows-detectors-queries-***) :
```
$ curl -k -XGET -u 'admin:password' 'https://<ip>:9200/_cat/indices' -s  | grep opensearch
green open .opensearch-notifications-config QDfok7N0SnmHHPXP4PEMlQ 1 2        0   0     624b     208b
green open .opensearch-observability        rBhEJuZxR3SPvspYqcQD6w 1 2        0   0     624b     208b
```

Manually created alias:
```
$ curl -H 'Content-Type: application/json' -k -XPOST -u 'admin:password' 'https://<ip>:9200/_aliases'  -d '{"actions":[{"add":{"index":".opensearch-sap-windows-detectors-queries-000001","alias":".opensearch-sap-windows-detectors-queries","is_write_index":true}}]}'
{"acknowledged":true}

$ curl -k -XGET -u 'admin:password' 'https://<ip>:9200/_cat/aliases' -s   | grep detector
.opensearch-sap-windows-detectors-queries .opensearch-sap-windows-detectors-queries-000001         - - - true
```

And try to create detector in OpenSearch Security Analytics and this detector create successfully.

**Comment by engechas** [comment]
Looks like the issue was resolved by manually creating the alias. Will close this issue. Please reopen if there is still a problem creating a detector
