### ISSUE TITLE
[BUG] Alerting error: "Filter by user backend roles is enabled with security disabled."

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/security-analytics#878]
A user reported the following via the [forum](https://forum.opensearch.org/t/opensearch-alerting-plugin-is-throwing-exception-filter-by-user-backend-roles-is-enabled-by-security-disabled/13685/2):

> I have recently upgraded the opensearch to 2.6 version and Alerting plugin is throwing exception
> Below is the exception showing when I open the monitor or the alerting page
> 
> 
> ![image](https://github.com/opensearch-project/alerting/assets/3864750/817adaf9-8cec-4809-af05-f387f995d97e)
> 
> 
> I am not able to figure out the issue and the security admin script is also working and the cluster is security enabled
> 
> 

**Do you have any additional context?**
Here's an error log:

```
[2023-04-05T08:21:40,974][ERROR][o.o.a.u.AlertingException] [olselkdev-manager-1] Alerting error: OpenSearchStatusException[Filter by user backend roles is enabled with security disabled.]
[2023-04-05T08:21:40,975][ERROR][o.o.a.t.TransportGetAlertsAction] [olselkdev-manager-1] Failed to get alerts
org.opensearch.alerting.util.AlertingException: Filter by user backend roles is enabled with security disabled.
at org.opensearch.alerting.util.AlertingException$Companion.wrap(AlertingException.kt:70) ~[?:?]
at org.opensearch.alerting.transport.SecureTransportAction$DefaultImpls.validateUserBackendRoles(SecureTransportAction.kt:82) ~[?:?]
at org.opensearch.alerting.transport.TransportGetMonitorAction.validateUserBackendRoles(TransportGetMonitorAction.kt:36) ~[?:?]
at org.opensearch.alerting.transport.TransportGetMonitorAction.doExecute(TransportGetMonitorAction.kt:61) ~[?:?]
at org.opensearch.alerting.transport.TransportGetMonitorAction.doExecute(TransportGetMonitorAction.kt:36) ~[?:?]
at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:118) ~[?:?]
at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:264) ~[?:?]
at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:149) ~[?:?]
at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78) ~[?:?]
at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:465) ~[opensearch-2.6.0.jar:2.6.0]
at org.opensearch.alerting.transport.TransportGetAlertsAction$resolveAlertsIndexName$2$getMonitorResponse$1.invoke(TransportGetAlertsAction.kt:165) ~[opensearch-alerting-2.6.0.0.jar:2.6.0.0]
at org.opensearch.alerting.transport.TransportGetAlertsAction$resolveAlertsIndexName$2$getMonitorResponse$1.invoke(TransportGetAlertsAction.kt:164) ~[opensearch-alerting-2.6.0.0.jar:2.6.0.0]
at org.opensearch.alerting.opensearchapi.OpenSearchExtensionsKt.suspendUntil(OpenSearchExtensions.kt:153) ~[alerting-core-2.6.0.0.jar:?]
at org.opensearch.alerting.transport.TransportGetAlertsAction$resolveAlertsIndexName$2.invokeSuspend(TransportGetAlertsAction.kt:164) ~[opensearch-alerting-2.6.0.0.jar:2.6.0.0]
at org.opensearch.alerting.transport.TransportGetAlertsAction$resolveAlertsIndexName$2.invoke(TransportGetAlertsAction.kt) ~[opensearch-alerting-2.6.0.0.jar:2.6.0.0]
at org.opensearch.alerting.transport.TransportGetAlertsAction$resolveAlertsIndexName$2.invoke(TransportGetAlertsAction.kt) ~[opensearch-alerting-2.6.0.0.jar:2.6.0.0]
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91) ~[kotlinx-coroutines-core-1.1.1.jar:?]
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:146) ~[kotlinx-coroutines-core-1.1.1.jar:?]
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source) ~[kotlinx-coroutines-core-1.1.1.jar:?]
at org.opensearch.alerting.transport.TransportGetAlertsAction.resolveAlertsIndexName(TransportGetAlertsAction.kt:156) ~[opensearch-alerting-2.6.0.0.jar:2.6.0.0]
at org.opensearch.alerting.transport.TransportGetAlertsAction$doExecute$1$1.invokeSuspend(TransportGetAlertsAction.kt:132) [opensearch-alerting-2.6.0.0.jar:2.6.0.0]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.10.jar:1.6.10-release-923(1.6.10)]
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]
Caused by: java.lang.Exception: org.opensearch.OpenSearchStatusException: Filter by user backend roles is enabled with security disabled.
```

**Comment by Sreekanth-hubs** [comment]
https://forum.opensearch.org/t/alerting-backend-roles-not-working-even-after-enabling-the-backend-roles/21353

Can anyone please help me on this above one.

**Comment by wbrown-ping** [comment]
Still seeing this on OpenSearch 2.11.1, can we get some traction on this? TIA 

Steps for reproduction:
1. Create a new monitor, trigger
2. Do some change to enact the trigger/monitor, and create a alert
3.  Attempt to acknowledge the alert from any page (alerts, or monitor view). 
4.  See that the request times out in UI, and we get below error in logs.  

```
[2025-02-14T19:47:24,045][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [opensearch-cluster-hot-1] uncaught exception in thread [DefaultDispatcher-worker-2]                                                                                  org.opensearch.alerting.util.AlertingException: Filter by user backend roles is enabled with security disabled.        

```

Env info:
Version 2.11.11
"plugins.alerting.filter_by_backend_roles": "true"
User roles: 
```
kibana_user
alerting_full_access
all_access

```

![Image](https://github.com/user-attachments/assets/c566c97e-0e7d-44e8-b9cc-dd28655d0bf3)

Side note, why does it say that security is disabled in log message?  I am notified via logs that security is enabled/initialized on startup `Enabling OpenSearch Security Plugin`.

**Comment by cwperks** [comment]
I'm not an expert on this plugin or the alerting plugin, but the issue is [here](https://github.com/opensearch-project/alerting/blob/ef88cf35aa102f0bd6b27b889cd159da78ebb154/alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt#L86-L97) where I don't believe it should be stashing before executing the transportGetMonitorAction

**Comment by AWSHurneyt** [comment]
Tagging @Murali-Arigala to add this to the team's tasks.
